site_name: 虾七八写
# Copyright
copyright: 'Copyright &copy; 2018 Wu Jun'
theme:
  name: material
  custom_dir: theme/
  feature:
    tabs: true
  language: 'zh'
extra_css:
  - assets/stylesheets/mdc-web.css
  # - assets/stylesheets/material-components-web.min.css
nav:
    - 首页: 'index.md'
    - 巧克力租客:
      - '1.1': 'Chocolate-Renter/巧克力租客-1.1.md'
      - '1.2': 'Chocolate-Renter/巧克力租客-1.2.md'
      - '1.3': 'Chocolate-Renter/巧克力租客-1.3.md'
      - '1.4': 'Chocolate-Renter/巧克力租客-1.4.md'
      - '1.5': 'Chocolate-Renter/巧克力租客-1.5.md'
      - '1.6': 'Chocolate-Renter/巧克力租客-1.6.md'
      - '2.1': 'Chocolate-Renter/巧克力租客-2.1.md'
      - '2.2': 'Chocolate-Renter/巧克力租客-2.2.md'
      - '2.3': 'Chocolate-Renter/巧克力租客-2.3.md'
      - '2.4': 'Chocolate-Renter/巧克力租客-2.4.md'
      - '2.5': 'Chocolate-Renter/巧克力租客-2.5.md'
      - '2.6': 'Chocolate-Renter/巧克力租客-2.6.md'
      - '3.1': 'Chocolate-Renter/巧克力租客-3.1.md'
      - '3.2': 'Chocolate-Renter/巧克力租客-3.2.md'
      - '3.3': 'Chocolate-Renter/巧克力租客-3.3.md'
      - '3.4': 'Chocolate-Renter/巧克力租客-3.4.md'
      - '3.5': 'Chocolate-Renter/巧克力租客-3.5.md'
      - '3.6': 'Chocolate-Renter/巧克力租客-3.6.md'
      - '3.7': 'Chocolate-Renter/巧克力租客-3.7.md'
      - '3.8': 'Chocolate-Renter/巧克力租客-3.8.md'
    - 乱尘妃子:
      - '1.1': 'Immoral-Love/乱尘妃子-1.1.md'
      - '1.2': 'Immoral-Love/乱尘妃子-1.2.md'
      - '1.3': 'Immoral-Love/乱尘妃子-1.3.md'
      - '1.4': 'Immoral-Love/乱尘妃子-1.4.md'
      - '1.5': 'Immoral-Love/乱尘妃子-1.5.md'
      - '1.6': 'Immoral-Love/乱尘妃子-1.6.md'
      - '1.7': 'Immoral-Love/乱尘妃子-1.7.md'
      - '1.8': 'Immoral-Love/乱尘妃子-1.8.md'
      - '1.9': 'Immoral-Love/乱尘妃子-1.9.md'
      - '1.10': 'Immoral-Love/乱尘妃子-1.10.md'
      - '1.11': 'Immoral-Love/乱尘妃子-1.11.md'
      - '1.12': 'Immoral-Love/乱尘妃子-1.12.md'
      - '1.13': 'Immoral-Love/乱尘妃子-1.13.md'
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - smarty:
      smart_quotes: false
  - attr_list
  - def_list
  - tables
  - abbr
  - footnotes
  - codehilite:
       guess_lang: true
  - pymdownx.extrarawhtml:
  - pymdownx.betterem:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences: 
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: sequence
          class: uml-sequence-diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      user: facelessuser
      repo: pymdown-extensions
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details: